<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-10T09:14:35 IST" name="Suite" finished-at="2023-07-10T09:14:42 IST" duration-ms="7862">
    <groups>
    </groups>
    <test started-at="2023-07-10T09:14:35 IST" name="Test" finished-at="2023-07-10T09:14:42 IST" duration-ms="7862">
      <class name="com.LoginTest.VerifyTC_002">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.LoginTest.VerifyTC_002@38089a5a]" started-at="2023-07-10T09:14:40 IST" name="setUp" finished-at="2023-07-10T09:14:42 IST" duration-ms="2260" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyTC_002_loginInvalidCredentials()[pri:0, instance:com.LoginTest.VerifyTC_002@38089a5a]" started-at="2023-07-10T09:14:42 IST" name="verifyTC_002_loginInvalidCredentials" finished-at="2023-07-10T09:14:42 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTC_002_loginInvalidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.LoginTest.VerifyTC_002@38089a5a]" started-at="2023-07-10T09:14:42 IST" name="tearDown" finished-at="2023-07-10T09:14:42 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.LoginTest.VerifyTC_002 -->
      <class name="com.LoginTest.VerifyTC_001">
        <test-method is-config="true" signature="initilizationObject()[pri:0, instance:com.LoginTest.VerifyTC_001@5d066c7d]" started-at="2023-07-10T09:14:34 IST" name="initilizationObject" finished-at="2023-07-10T09:14:35 IST" duration-ms="962" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilizationObject -->
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.LoginTest.VerifyTC_001@5d066c7d]" started-at="2023-07-10T09:14:35 IST" name="setUp" finished-at="2023-07-10T09:14:39 IST" duration-ms="4396" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyTC_001_loginvalidCredentials()[pri:0, instance:com.LoginTest.VerifyTC_001@5d066c7d]" started-at="2023-07-10T09:14:39 IST" name="verifyTC_001_loginvalidCredentials" finished-at="2023-07-10T09:14:39 IST" duration-ms="332" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.LoginTest.VerifyTC_001.verifyTC_001_loginvalidCredentials(VerifyTC_001.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTC_001_loginvalidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.LoginTest.VerifyTC_001@5d066c7d]" started-at="2023-07-10T09:14:40 IST" name="tearDown" finished-at="2023-07-10T09:14:40 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.LoginTest.VerifyTC_001 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
